"""
Django settings for sondage_project project.

Generated by 'django-admin startproject' using Django 5.0.3.

For more information on this file, see
https://docs.djangoproject.com/en/5.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.0/ref/settings/
"""

from pathlib import Path
import os
from decouple import config, Csv

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = config('SECRET_KEY', default='django-insecure-your-secret-key-here-change-in-production')

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = config('DEBUG', default=True, cast=bool)

ALLOWED_HOSTS = config('ALLOWED_HOSTS', default='localhost,127.0.0.1', cast=Csv())


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'surveys',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'surveys.middleware.AdminSetupMiddleware',
    'surveys.error_handlers.GlobalErrorHandlerMiddleware',  # Gestion globale des erreurs
]

ROOT_URLCONF = 'sondage_project.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'sondage_project.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.0/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.0/topics/i18n/

LANGUAGE_CODE = 'fr-fr'

TIME_ZONE = 'Africa/Kinshasa'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.0/howto/static-files/

STATIC_URL = 'static/'
STATICFILES_DIRS = [BASE_DIR / 'static']
STATIC_ROOT = BASE_DIR / 'staticfiles'

MEDIA_URL = 'media/'
MEDIA_ROOT = BASE_DIR / 'media'

# Default primary key field type
# https://docs.djangoproject.com/en/5.0/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# Configuration pour gros volumes de données
DATA_UPLOAD_MAX_NUMBER_FIELDS = 10000  # Augmenté pour support de gros sondages
FILE_UPLOAD_MAX_MEMORY_SIZE = 10485760  # 10MB

# Export settings
EXPORT_MAX_RESPONSES_PER_PAGE = 50  # Nombre de réponses par page dans les exports
EXPORT_DEFAULT_LIMIT = 100  # Limite par défaut pour les exports
EXPORT_MAX_LIMIT = 5000  # Limite maximale pour un export unique

# ==============================================================================
# LOGGING CONFIGURATION PROFESSIONNELLE
# ==============================================================================

import os

# Créer le dossier logs s'il n'existe pas
LOGS_DIR = BASE_DIR / 'logs'
if not os.path.exists(LOGS_DIR):
    os.makedirs(LOGS_DIR)

LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    
    # Formatage des logs
    'formatters': {
        'verbose': {
            'format': '[{levelname}] {asctime} {module} {process:d} {thread:d} - {message}',
            'style': '{',
            'datefmt': '%Y-%m-%d %H:%M:%S',
        },
        'simple': {
            'format': '[{levelname}] {asctime} - {message}',
            'style': '{',
            'datefmt': '%Y-%m-%d %H:%M:%S',
        },
        'detailed': {
            'format': '''
================================================================================
[{levelname}] {asctime}
Module: {module} | Function: {funcName} | Line: {lineno}
Process: {process} | Thread: {thread}
Message: {message}
================================================================================
''',
            'style': '{',
            'datefmt': '%Y-%m-%d %H:%M:%S',
        }
    },
    
    # Filtres
    'filters': {
        'require_debug_true': {
            '()': 'django.utils.log.RequireDebugTrue',
        },
        'require_debug_false': {
            '()': 'django.utils.log.RequireDebugFalse',
        },
    },
    
    # Handlers (où vont les logs)
    'handlers': {
        # Console en développement
        'console': {
            'level': 'INFO',
            'filters': ['require_debug_true'],
            'class': 'logging.StreamHandler',
            'formatter': 'simple',
        },
        
        # Fichier pour toutes les erreurs
        'file_errors': {
            'level': 'ERROR',
            'class': 'logging.handlers.RotatingFileHandler',
            'filename': LOGS_DIR / 'errors.log',
            'maxBytes': 10485760,  # 10MB
            'backupCount': 10,
            'formatter': 'detailed',
        },
        
        # Fichier pour les erreurs critiques uniquement
        'file_critical': {
            'level': 'CRITICAL',
            'class': 'logging.handlers.RotatingFileHandler',
            'filename': LOGS_DIR / 'critical.log',
            'maxBytes': 5242880,  # 5MB
            'backupCount': 5,
            'formatter': 'detailed',
        },
        
        # Fichier pour les activités générales
        'file_general': {
            'level': 'INFO',
            'class': 'logging.handlers.RotatingFileHandler',
            'filename': LOGS_DIR / 'general.log',
            'maxBytes': 10485760,  # 10MB
            'backupCount': 5,
            'formatter': 'verbose',
        },
        
        # Fichier spécifique pour les erreurs de l'application surveys
        'file_surveys': {
            'level': 'WARNING',
            'class': 'logging.handlers.RotatingFileHandler',
            'filename': LOGS_DIR / 'surveys.log',
            'maxBytes': 10485760,  # 10MB
            'backupCount': 5,
            'formatter': 'verbose',
        },
        
        # Email aux admins pour les erreurs critiques (production)
        'mail_admins': {
            'level': 'ERROR',
            'filters': ['require_debug_false'],
            'class': 'django.utils.log.AdminEmailHandler',
            'include_html': True,
        }
    },
    
    # Loggers (qui log quoi)
    'loggers': {
        # Logger Django général
        'django': {
            'handlers': ['console', 'file_general', 'mail_admins'],
            'level': 'INFO',
            'propagate': False,
        },
        
        # Logger pour les erreurs Django
        'django.request': {
            'handlers': ['file_errors', 'mail_admins'],
            'level': 'ERROR',
            'propagate': False,
        },
        
        # Logger pour les erreurs de sécurité
        'django.security': {
            'handlers': ['file_critical', 'mail_admins'],
            'level': 'WARNING',
            'propagate': False,
        },
        
        # Logger spécifique pour l'application surveys
        'surveys': {
            'handlers': ['console', 'file_surveys'],
            'level': 'INFO',
            'propagate': False,
        },
        
        # Logger pour les erreurs de surveys
        'surveys.errors': {
            'handlers': ['file_errors', 'file_critical', 'mail_admins'],
            'level': 'ERROR',
            'propagate': False,
        },
        
        # Logger pour les opérations sensibles (exports, modifications...)
        'surveys.operations': {
            'handlers': ['file_surveys'],
            'level': 'INFO',
            'propagate': False,
        },
    },
    
    # Logger racine (catch-all)
    'root': {
        'handlers': ['console', 'file_general'],
        'level': 'WARNING',
    },
}

# ==============================================================================
# GESTION DES ERREURS PERSONNALISÉES
# ==============================================================================

# En production, ne jamais afficher les détails techniques
# DEBUG doit être False en production
if not DEBUG:
    # Configurations de sécurité renforcées pour la production
    SECURE_SSL_REDIRECT = True
    SESSION_COOKIE_SECURE = True
    CSRF_COOKIE_SECURE = True
    SECURE_BROWSER_XSS_FILTER = True
    SECURE_CONTENT_TYPE_NOSNIFF = True
    X_FRAME_OPTIONS = 'DENY'
    SECURE_HSTS_SECONDS = 31536000  # 1 an
    SECURE_HSTS_INCLUDE_SUBDOMAINS = True
    SECURE_HSTS_PRELOAD = True

