# Generated by Django 6.0.1 on 2026-03-25 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('surveys', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='response',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='response',
            name='participant_email',
            field=models.EmailField(blank=True, default='', max_length=254, verbose_name='Email du participant'),
        ),
        migrations.AlterField(
            model_name='response',
            name='participant_name',
            field=models.CharField(default='Anonyme', max_length=100, verbose_name='Nom du participant'),
        ),
    ]
